import "@/app/globals.css";
import RootTabs from "@/components/main/RootTabs";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { Vazirmatn } from "next/font/google";

const vazirmatn = Vazirmatn({ subsets: ["arabic"] });
export const metadata = {
  manifest: "/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport = {
  themeColor: "#2563eb",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={vazirmatn.className} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster/>
          {children}
          <RootTabs />
        </ThemeProvider>
      </body>
    </html>
  );
}
